### PR TITLE
Rework toolbar

### PR DESCRIPTION
**Pull request by mrtcode**

### CODE REVIEW

**Comment by dstillman** [comment]
This is nice.

Some things I noticed:

1. The paragraph, alignment, and three-dots menus should open aligned with the bottom of the button background, not the bottom of the toolbar. (Search is a panel within the text area, so that's different. These are popups.)
2. Clicking on Aa again while the menu is open should close the menu.
3. Insert Citation and Search seem to trigger on mousedown rather than click like the others.
4. Maybe we can't do anything about this because we have to parse arbitrary HTML, but it's still pretty weird that the paragraph styles aren't mutually exclusive — I don't think there's really any reason you would need to create a header in list item, and it looks like a mistake for, say, Paragraph and Bulleted List to be selected. At the very least I would show Paragraph as deselected when in a list, since that's the default case. But if there's any way we can just say that for new content these should just be mutually exclusive, that would be better.
5. Blockquote seems to be effectively a button rather than a toggle. Is that on purpose, so that you can create multiple levels of blockquotes? Weird for it to be in this menu if that's the case.
6. In a list, alignment only affects the text, not the bullet itself. Compare to TinyMCE, where the list itself is centered, which is the current behavior.
7. Show in Library shouldn't appear in the library view.

**Comment by dstillman** [comment]
8. Similar to Text Format, Alignment doesn't close when the button is clicked again.
9. Actually, if we're going to be consistent with other menus in the program, the menus should open on mousedown, rather than click. Click makes the interface feel much slower. The buttons should still be on click.

**Comment by dstillman** [comment]
10. I don't know if this is fixable without making the icon blurrier, but the search icon is a little too big, with the handle going down too far. Compare to the design:

toolbar

**Comment by mrtcode** [comment]
Thanks for good points!

> 6. In a list, alignment only affects the text, not the bullet itself. Compare to TinyMCE, where the list itself is centered, which is the current behavior.

For me, on TinyMCE, list bullet points aren't affected when applying alignment. Can you explain what exactly do you mean here?

**Comment by dstillman** [comment]
Sorry, my comparison was to the [TinyMCE 5 demo](https://www.tiny.cloud/docs/demo/full-featured/) — I hadn't tested with TinyMCE in Zotero, which does indeed center just the text.

tinymce-center-list

If we're able to do that, that'd be better.

**Comment by dstillman** [comment]
Though, actually, the [TinyMCE 4 demo](https://www.tiny.cloud/docs-4x/demo/full-featured/) gets it right too:

tinymce4-center-list

I'm not sure why we get it wrong with our TinyMCE integration.

**Comment by mrtcode** [comment]
Yeah, on FF the bullet is centered as well, although on Chrome the behaviour is like in our client. But allowing to indent and center specific list element is a complete mess anyway. Are we sure want that at all?

Additionally, our schema fails to import/save this alignment for list items.

**Comment by dstillman** [comment]
Oh, I didn't see that TinyMCE allowed different alignments for each list item. There's certainly no need for that.

The current behavior is definitely wrong, so I'd say we either apply the alignment to the whole list or just disable the alignment options altogether when in a list. I'm fine with the latter.

**Pull request merged**
