### PR TITLE
Show annotation colors

### PR DESCRIPTION
**Pull request by mrtcode**
This PR is just to try out how colors feel in `note-editor` in general, as discussed in zotero/zotero#2081. And there are more issues to discuss before moving further:

- Dragged text doesn't have any color.
- No color visible for image annotation yet. We could draw a colorful frame around it.
- No color for note annotation and other annotations comments. Because comments are inserted as plain text, they don't carry any information about the color, and also it would be quite difficult to make that color toggleable.
- Colors are always enabled and not toggleable, at the moment, because the current more button popup is not capable to show checkmarks, therefore, maybe, we should switch to XUL popup here.
- We should increase annotation color opacity. It's currently 50%, just like in `pdf-reader`.

### CODE REVIEW

**Comment by mrtcode** [comment]
Alternatively, we could use `note-editor` background color formatting option to highlight the necessary text. That would work only for newly inserted annotations, and wouldn't be toggleable, but highlighting with background color tool is already existing practice and would allow to change the color. And there won't be disparity between toggleable, integrated color and the color you highlight manually to other text.

**Comment by dstillman** [comment]
I think it should be toggleable. We're storing the color as a property anyway, so it really seems more appropriate as display option that you might turn on or off at different points in your process, and you shouldn't have to decide ahead of time whether annotations you're adding to your notes will be colored or not.

(I don't know what happens if you highlight annotation text and assign a background color, though.)

**Comment by mrtcode** [comment]
Right, but I mean not being able to control (change, delete, join with other text) annotation colors in notes is really limiting.

Additionally, annotation color is immediately lost if you delete one of the quotation marks.

I really feel that annotation colors should somehow converge with highlighter tool.

**Comment by dstillman** [comment]
It seems like it would have to be something like an "Apply Annotation Colors" menu option in the three-dots menu, as well as a general option to "Automatically apply annotation colors when adding annotations to notes" in the preferences.

And the option would become disabled if all annotations in the document fully matched their annotation colors?

If you highlighted an annotation differently, I guess the three-dots menu option would become enabled again and override that?

**Comment by mrtcode** [comment]
Something like that could work. Colors would be enabled by default?

How about image and note annotations? Inserted note annotations don't have any information about color at all. Image annotations have color, but making `note-editor` text highlighter tool to affect image annotation color is more challenging and also the same problem applies when inserting to other word processors.

**Comment by dstillman** [comment]
I think they'd be disabled by default. We didn't launch with that, and I think that's reasonable — we're viewing them more as an organizational tool within the reader (which will be more useful when you can filter by color from a [color/tag selector](https://github.com/zotero/zotero/issues/2078)). If your workflow really calls for this, I think that's a choice you make.

I think we can ignore color for note and image annotations.

**Comment by mrtcode** [comment]
This big update involves the recent toolbar redesign, highlighting tool that is optimized for highlight annotations, "Apply Annotation Colors" in more menu, and some other internal changes. Therefore this PR will block further `note-editor` development.

This commit depends on another commit that is for the client, but it can be ignored for now. Only localizations ant context menu alignment submenu will be missing.

As I mentioned, the biggest problem is with our default colors. They are too intensive and need various hacks to apply the desired opacity. And that involves `note-editor`, TinyMCE editor, insertion to word processors, export to PDFs.

**Comment by dstillman** [comment]
sup-sub

Need to align the baseline of the x's in the subscript and superscript icons.

**Comment by dstillman** [comment]
Inline code input is a bit glitchy:

https://user-images.githubusercontent.com/783082/122363901-53b55900-cf27-11eb-9a44-ab55b98c5f1d.mov

The 'd' starts as normal text and then is turned into smaller monospaced text. If this only affects this mode, we can fix this after merging this.

**Comment by dstillman** [comment]
It looks like this applies a bit more generally, and isn't new — I'm seeing it for italics in the current build.

**Comment by dstillman** [comment]
This is great. And the highlight colors are actually neat enough that maybe it should do that by default.

What do we think about a "Remove All Annotation Colors" option that removed any background colors from annotation text? (I think it would remove any current background colors on annotation text even if they didn't match the underlying colors.)

**Comment by mrtcode** [comment]
I think "Remove All Annotation Colors" could be useful, but we can postpone this to see if people are actually asking for this. Because in most cases just selecting the whole note text and removing with highlighting tool might be sufficient.

Ok, I will investigate the inline code issue and then I will merge this.

**Comment by dstillman** [comment]
If we're going to default to including the colors, we should definitely have an option to clear them all. Yes, Select All + color + X would do it, if you think to do that, but many people won't, and that would also clear any other highlighting.

**Comment by mrtcode** [comment]
Yeah, we can have it, but, for now, I think, let's not do automatic colors and just see if people are happy with this workflow in general.

**Pull request merged**
